Repository wasp-lang/wasp, pull requests merged in 2024-02, with the labels that each got.

#1737 Removes AuthError
  examples/realworld/src/server/user/actions.js
  waspc/data/Generator/templates/sdk/auth/utils.ts
  waspc/data/Generator/templates/sdk/package.json
  waspc/data/Generator/templates/sdk/server/AuthError.ts
  waspc/data/Generator/templates/sdk/server/index.ts
  waspc/data/Generator/templates/server/src/auth/utils.ts
  waspc/examples/todo-typescript/src/task/queries.ts
  waspc/src/Wasp/Generator/SdkGenerator.hs
  web/docs/auth/overview.md
Labels: restructuring

#1729 Updated docs/advanced/apis to 0.12.
  web/docs/advanced/apis.md
Labels: documentation

#1730 Updated docs/advanced/middleware-config to 0.12.
  web/docs/advanced/middleware-config.md
Labels: documentation

#1732 Updated docs/advanced/links to 0.12.
  web/docs/advanced/links.md
Labels: documentation

#1733 Updated docs/advanced/web-sockets to 0.12.
  web/docs/advanced/web-sockets.md
Labels: documentation

#1734 Updated docs/advanced/email to 0.12.
  web/docs/advanced/email/email.md
Labels: documentation

#1723 Auth docs rework
  web/docs/auth/_user-signup-fields-explainer.md
  web/docs/auth/email.md
  web/docs/auth/entities/_get-email.md
  web/docs/auth/entities/_get-username.md
  web/docs/auth/entities/entities.md
  web/docs/auth/migrate-from-11.md
  web/docs/auth/social-auth/github.md
  web/docs/auth/social-auth/google.md
  web/docs/auth/social-auth/overview.md
  web/docs/auth/ui.md
  web/docs/auth/username-and-pass.md
  web/versioned_docs/version-0.11.8/auth/overview.md
Labels: documentation

#1726 Wasp ai 0.12
  waspc/src/Wasp/AI/GenerateNewProject.hs
  waspc/src/Wasp/AI/GenerateNewProject/Common/Prompts.hs
  waspc/src/Wasp/AI/GenerateNewProject/Operation.hs
  waspc/src/Wasp/AI/GenerateNewProject/Page.hs
  waspc/src/Wasp/AI/GenerateNewProject/PageComponentFile.hs
  waspc/src/Wasp/AI/GenerateNewProject/Plan.hs
  waspc/src/Wasp/AI/GenerateNewProject/Skeleton.hs
  waspc/src/Wasp/AI/GenerateNewProject/WaspFile.hs
  waspc/test/AI/GenerateNewProject/PageComponentFileTest.hs
  waspc/waspc.cabal
Labels: restructuring

#1727 Migration guide for 0.12.x and examples
  examples/streaming/.gitignore
  examples/streaming/.waspignore
  examples/streaming/main.wasp
  examples/streaming/package-lock.json
  examples/streaming/package.json
  examples/streaming/public/.gitkeep
  examples/streaming/src/client/MainPage.jsx
  examples/streaming/src/client/tsconfig.json
  examples/streaming/src/server/streaming.ts
  examples/streaming/src/server/tsconfig.json
  examples/streaming/src/shared/tsconfig.json
  examples/streaming/src/vite-env.d.ts
  examples/streaming/tsconfig.json
  examples/streaming/vite.config.ts
  examples/todo-typescript/.gitignore
  examples/todo-typescript/main.wasp
  examples/todo-typescript/package-lock.json
  examples/todo-typescript/package.json
  examples/todo-typescript/src/client/LoginPage.tsx
  examples/todo-typescript/src/client/MainPage.tsx
  examples/todo-typescript/src/client/SignupPage.tsx
  examples/todo-typescript/src/client/tsconfig.json
  examples/todo-typescript/src/client/vite-env.d.ts
  examples/todo-typescript/src/server/actions.ts
  examples/todo-typescript/src/server/queries.ts
  examples/todo-typescript/src/server/tsconfig.json
  examples/todo-typescript/src/shared/tsconfig.json
  examples/todo-typescript/src/vite-env.d.ts
  examples/todo-typescript/tsconfig.json
  examples/todo-typescript/vite.config.ts
  waspc/data/Cli/templates/skeleton/.waspignore
  waspc/data/Generator/templates/sdk/client/index.ts
  waspc/waspc.cabal
  web/docs/auth/migrate-from-11.md
  web/docs/introduction/migrate-from-11.md
Labels: documentation, restructuring

#1744 Updates starter templates
  web/docs/project/starter-templates.md
  web/static/img/starter-templates/open-saas-banner.png
Labels: documentation

#1745 Updates general docs
  web/docs/general/cli.md
  web/docs/general/language.md
Labels: documentation

#1742 Updated examples/thoughts to 0.12.
  examples/thoughts/.gitignore
  examples/thoughts/main.wasp
  examples/thoughts/migrations/20240209145604_init/migration.sql
  examples/thoughts/package-lock.json
  examples/thoughts/package.json
  examples/thoughts/public/.gitkeep
  examples/thoughts/src/client/LoginPage.jsx
  examples/thoughts/src/client/MainPage.jsx
  examples/thoughts/src/client/SignupPage.jsx
  examples/thoughts/src/client/TagsSidebar.jsx
  examples/thoughts/src/client/ThoughtsPage.jsx
  examples/thoughts/src/client/TopNavbar.jsx
  examples/thoughts/src/client/jsconfig.json
  examples/thoughts/src/server/actions.js
  examples/thoughts/src/server/jsconfig.json
  examples/thoughts/src/server/queries.js
  examples/thoughts/src/shared/jsconfig.json
  examples/thoughts/src/vite-env.d.ts
  examples/thoughts/tsconfig.json
  examples/thoughts/vite.config.ts
Labels: restructuring

#1749 Updates client setup docs
  web/docs/project/client-config.md
Labels: documentation

#1753 Updates CSS frameworks docs
  web/docs/project/css-frameworks.md
Labels: documentation

#1751 Updates static assets docs
  web/docs/project/static-assets.md
Labels: documentation

#1754 Updates custom vite config docs
  web/docs/project/custom-vite-config.md
Labels: documentation

#1755 Exports HttpMethod and Route types from wasp/client
  waspc/data/Generator/templates/sdk/auth/useAuth.ts
  waspc/data/Generator/templates/sdk/client/index.ts
  waspc/data/Generator/templates/sdk/client/operations/internal/index.ts
  waspc/data/Generator/templates/sdk/client/operations/queries/core.d.ts
  waspc/data/Generator/templates/sdk/client/test/vitest/helpers.tsx
  waspc/data/Generator/templates/sdk/package.json
  waspc/data/Generator/templates/sdk/types/index.ts
Labels: restructuring

#1752 Update testing docs
  web/docs/project/testing.md
Labels: documentation

#1760 Migrates headless tests to new structure
  waspc/headless-test/examples/todoApp/package-lock.json
  waspc/headless-test/examples/todoApp/package.json
  waspc/headless-test/examples/todoApp/src/client/App.tsx
  waspc/headless-test/examples/todoApp/src/client/Todo.tsx
  waspc/headless-test/examples/todoApp/src/client/clientSetup.js
  waspc/headless-test/examples/todoApp/src/client/pages/About.jsx
  waspc/headless-test/examples/todoApp/src/client/pages/ProfilePage.tsx
  waspc/headless-test/examples/todoApp/src/client/pages/Task.tsx
  waspc/headless-test/examples/todoApp/src/client/pages/auth/EmailVerification.tsx
  waspc/headless-test/examples/todoApp/src/client/pages/auth/Login.tsx
  waspc/headless-test/examples/todoApp/src/client/pages/auth/PasswordReset.tsx
  waspc/headless-test/examples/todoApp/src/client/pages/auth/RequestPasswordReset.tsx
  waspc/headless-test/examples/todoApp/src/client/pages/auth/Signup.tsx
  waspc/headless-test/examples/todoApp/src/client/tsconfig.json
  waspc/headless-test/examples/todoApp/src/client/user.ts
  waspc/headless-test/examples/todoApp/src/client/vite-env.d.ts
  waspc/headless-test/examples/todoApp/src/server/actions.ts
  waspc/headless-test/examples/todoApp/src/server/apis.ts
  waspc/headless-test/examples/todoApp/src/server/auth/email.ts
  waspc/headless-test/examples/todoApp/src/server/dbSeeds.ts
  waspc/headless-test/examples/todoApp/src/server/jobs/bar.js
  waspc/headless-test/examples/todoApp/src/server/queries.ts
  waspc/headless-test/examples/todoApp/src/server/serverSetup.ts
  waspc/headless-test/examples/todoApp/src/server/tsconfig.json
  waspc/headless-test/examples/todoApp/src/shared/tsconfig.json
  waspc/headless-test/examples/todoApp/src/util.js
  waspc/headless-test/examples/todoApp/src/vite-env.d.ts
  waspc/headless-test/examples/todoApp/tailwind.config.cjs
  waspc/headless-test/examples/todoApp/todoApp.wasp
  waspc/headless-test/examples/todoApp/tsconfig.json
  waspc/headless-test/examples/todoApp/vite.config.ts
Labels: restructuring

#1763 Enables headless and unit tests
  .github/workflows/waspc-ci.yaml
  waspc/examples/todo-typescript/src/task/actions.ts
  waspc/headless-test/examples/todoApp/public/.gitkeep
Labels: restructuring

#1758 Expose server-side operations from SDK
  waspc/data/Generator/templates/sdk/server/operations/index.ts
  waspc/examples/todo-typescript/main.wasp
  waspc/examples/todo-typescript/src/jobs/print.ts
  waspc/examples/todo-typescript/src/setup/serverSetup.ts
  waspc/examples/todo-typescript/src/task/queries.ts
  waspc/src/Wasp/Generator/SdkGenerator/Server/OperationsGenerator.hs
Labels: restructuring, new sdk api

#1766 Fixes Tailwind setup in client tests
  waspc/examples/todo-typescript/package-lock.json
  waspc/src/Wasp/Generator/SdkGenerator.hs
  waspc/src/Wasp/Generator/WebAppGenerator.hs
Labels: restructuring

#1773 Make build work for 0.12.0
  waspc/cli/src/Wasp/Cli/Command/Build.hs
  waspc/cli/src/Wasp/Cli/Command/Start.hs
  waspc/data/Generator/templates/Dockerfile
  waspc/data/Generator/templates/react-app/vite.config.ts
  waspc/data/Generator/templates/sdk/client/webSocket/WebSocketProvider.tsx
  waspc/data/Generator/templates/sdk/package.json
  waspc/data/Generator/templates/sdk/server/_types/serialization.ts
  waspc/data/Generator/templates/sdk/tsconfig.json
  waspc/examples/todo-typescript/main.wasp
  waspc/examples/todo-typescript/package-lock.json
  waspc/examples/todo-typescript/src/MainPage.tsx
  waspc/examples/todo-typescript/src/task/actions.ts
  waspc/examples/todo-typescript/src/task/queries.ts
  waspc/examples/todo-typescript/src/user/auth.tsx
  waspc/examples/todo-typescript/src/user/customEmailSending.ts
  waspc/src/Wasp/Generator/DbGenerator/Jobs.hs
  waspc/src/Wasp/Generator/DockerGenerator.hs
  waspc/src/Wasp/Generator/SdkGenerator.hs
  waspc/src/Wasp/Generator/SdkGenerator/Common.hs
  waspc/src/Wasp/Generator/ServerGenerator.hs
  waspc/src/Wasp/Node/Version.hs
Labels: restructuring

#1821 Fixes the order of operations in `wasp build`
  waspc/cli/src/Wasp/Cli/Command/Build.hs
Labels: restructuring
